"""RESTMixin: the flat ``bot.<verb>_<resource>()`` surface.

Each attribute is a thin async delegation to a resource module function,
generated by ``_delegate()`` instead of written out, so this file never
holds a hand-maintained copy of every resource signature. ``functools.wraps``
carries the target's docstring and real parameters through to the generated
API reference; the ``__name__`` fixup at the end restores the public name for
the handful of methods that point at a differently named function (e.g.
``fetch_application`` delegates to ``application.fetch_current_application``).

Referencing a function that no longer exists fails at import time here rather
than silently dropping the method.
"""

import functools
from collections.abc import Callable, Coroutine
from typing import Any, Concatenate, ParamSpec, TypeVar

from . import (
    application,
    application_commands,
    audit_log,
    auto_moderation,
    channels,
    emojis,
    entitlements,
    guilds,
    invites,
    members,
    messages,
    scheduled_events,
    skus,
    soundboard,
    stage_instances,
    stickers,
    subscriptions,
    templates,
    threads,
    users,
    voice,
    webhooks,
)

_P = ParamSpec("_P")
_R = TypeVar("_R")


def _delegate(
    fn: Callable[_P, Coroutine[Any, Any, _R]],
) -> Callable[Concatenate[Any, _P], Coroutine[Any, Any, _R]]:
    """An async method that forwards straight to ``fn``. ``self`` is dropped;
    every argument goes through unchanged."""

    @functools.wraps(fn)
    async def method(self: object, *args: Any, **kwargs: Any) -> _R:
        return await fn(*args, **kwargs)

    return method


class RESTMixin:
    # -- application --
    fetch_application = _delegate(application.fetch_current_application)
    edit_application = _delegate(application.edit_current_application)
    fetch_application_role_connection_metadata = _delegate(application.fetch_application_role_connection_metadata)
    edit_application_role_connection_metadata = _delegate(application.edit_application_role_connection_metadata)

    # -- application commands --
    fetch_global_commands = _delegate(application_commands.fetch_global_commands)
    create_global_command = _delegate(application_commands.create_global_command)
    fetch_global_command = _delegate(application_commands.fetch_global_command)
    edit_global_command = _delegate(application_commands.edit_global_command)
    delete_global_command = _delegate(application_commands.delete_global_command)
    bulk_overwrite_global_commands = _delegate(application_commands.bulk_overwrite_global_commands)
    fetch_guild_commands = _delegate(application_commands.fetch_guild_commands)
    create_guild_command = _delegate(application_commands.create_guild_command)
    fetch_guild_command = _delegate(application_commands.fetch_guild_command)
    edit_guild_command = _delegate(application_commands.edit_guild_command)
    delete_guild_command = _delegate(application_commands.delete_guild_command)
    bulk_overwrite_guild_commands = _delegate(application_commands.bulk_overwrite_guild_commands)
    fetch_guild_command_permissions = _delegate(application_commands.fetch_guild_command_permissions)
    fetch_command_permissions = _delegate(application_commands.fetch_command_permissions)

    # -- entitlements and skus --
    fetch_entitlements = _delegate(entitlements.fetch_entitlements)
    fetch_entitlement = _delegate(entitlements.fetch_entitlement)
    consume_entitlement = _delegate(entitlements.consume_entitlement)
    create_test_entitlement = _delegate(entitlements.create_test_entitlement)
    delete_test_entitlement = _delegate(entitlements.delete_test_entitlement)
    fetch_skus = _delegate(skus.fetch_skus)
    fetch_sku_subscriptions = _delegate(subscriptions.fetch_sku_subscriptions)
    fetch_sku_subscription = _delegate(subscriptions.fetch_sku_subscription)

    # -- users --
    fetch_current_user = _delegate(users.fetch_current_user)
    fetch_user = _delegate(users.fetch_user)
    edit_current_user = _delegate(users.edit_current_user)
    fetch_current_user_guilds = _delegate(users.fetch_current_user_guilds)
    leave_guild = _delegate(users.leave_guild)
    create_dm = _delegate(users.create_dm)

    # -- audit log --
    fetch_audit_log = _delegate(audit_log.fetch_audit_log)

    # -- guild templates --
    fetch_template = _delegate(templates.fetch_template)
    fetch_guild_templates = _delegate(templates.fetch_guild_templates)
    create_guild_template = _delegate(templates.create_guild_template)
    sync_guild_template = _delegate(templates.sync_guild_template)
    edit_guild_template = _delegate(templates.edit_guild_template)
    delete_guild_template = _delegate(templates.delete_guild_template)

    # -- stage instances --
    create_stage_instance = _delegate(stage_instances.create_stage_instance)
    fetch_stage_instance = _delegate(stage_instances.fetch_stage_instance)
    edit_stage_instance = _delegate(stage_instances.edit_stage_instance)
    delete_stage_instance = _delegate(stage_instances.delete_stage_instance)

    # -- auto moderation --
    fetch_auto_moderation_rules = _delegate(auto_moderation.fetch_auto_moderation_rules)
    fetch_auto_moderation_rule = _delegate(auto_moderation.fetch_auto_moderation_rule)
    create_auto_moderation_rule = _delegate(auto_moderation.create_auto_moderation_rule)
    edit_auto_moderation_rule = _delegate(auto_moderation.edit_auto_moderation_rule)
    delete_auto_moderation_rule = _delegate(auto_moderation.delete_auto_moderation_rule)

    # -- guild scheduled events --
    fetch_guild_scheduled_events = _delegate(scheduled_events.fetch_guild_scheduled_events)
    create_guild_scheduled_event = _delegate(scheduled_events.create_guild_scheduled_event)
    fetch_guild_scheduled_event = _delegate(scheduled_events.fetch_guild_scheduled_event)
    edit_guild_scheduled_event = _delegate(scheduled_events.edit_guild_scheduled_event)
    delete_guild_scheduled_event = _delegate(scheduled_events.delete_guild_scheduled_event)
    fetch_guild_scheduled_event_users = _delegate(scheduled_events.fetch_guild_scheduled_event_users)

    # -- emojis --
    fetch_guild_emojis = _delegate(emojis.fetch_guild_emojis)
    fetch_guild_emoji = _delegate(emojis.fetch_guild_emoji)
    create_guild_emoji = _delegate(emojis.create_guild_emoji)
    edit_guild_emoji = _delegate(emojis.edit_guild_emoji)
    delete_guild_emoji = _delegate(emojis.delete_guild_emoji)
    fetch_application_emojis = _delegate(emojis.fetch_application_emojis)
    fetch_application_emoji = _delegate(emojis.fetch_application_emoji)
    create_application_emoji = _delegate(emojis.create_application_emoji)
    edit_application_emoji = _delegate(emojis.edit_application_emoji)
    delete_application_emoji = _delegate(emojis.delete_application_emoji)

    # -- soundboard --
    send_soundboard_sound = _delegate(soundboard.send_soundboard_sound)
    fetch_default_soundboard_sounds = _delegate(soundboard.fetch_default_soundboard_sounds)
    fetch_guild_soundboard_sounds = _delegate(soundboard.fetch_guild_soundboard_sounds)
    fetch_guild_soundboard_sound = _delegate(soundboard.fetch_guild_soundboard_sound)
    create_guild_soundboard_sound = _delegate(soundboard.create_guild_soundboard_sound)
    edit_guild_soundboard_sound = _delegate(soundboard.edit_guild_soundboard_sound)
    delete_guild_soundboard_sound = _delegate(soundboard.delete_guild_soundboard_sound)

    # -- stickers --
    fetch_sticker = _delegate(stickers.fetch_sticker)
    fetch_sticker_packs = _delegate(stickers.fetch_sticker_packs)
    fetch_sticker_pack = _delegate(stickers.fetch_sticker_pack)
    fetch_guild_stickers = _delegate(stickers.fetch_guild_stickers)
    fetch_guild_sticker = _delegate(stickers.fetch_guild_sticker)
    create_guild_sticker = _delegate(stickers.create_guild_sticker)
    edit_guild_sticker = _delegate(stickers.edit_guild_sticker)
    delete_guild_sticker = _delegate(stickers.delete_guild_sticker)

    # -- invites --
    fetch_invite = _delegate(invites.fetch_invite)
    delete_invite = _delegate(invites.delete_invite)
    fetch_invite_target_users = _delegate(invites.fetch_invite_target_users)
    edit_invite_target_users = _delegate(invites.edit_invite_target_users)
    fetch_invite_target_users_job_status = _delegate(invites.fetch_invite_target_users_job_status)

    # -- webhooks (bot token) --
    # create_webhook/get_channel_webhooks/delete_webhook already live on
    # Cordless itself (app.py) and delegate to webhooks.py directly, same
    # reason messages.py has no bot.create_message().
    fetch_channel_webhooks = _delegate(webhooks.fetch_channel_webhooks)
    fetch_guild_webhooks = _delegate(webhooks.fetch_guild_webhooks)
    fetch_webhook = _delegate(webhooks.fetch_webhook)
    edit_webhook = _delegate(webhooks.edit_webhook)

    # -- messages and reactions --
    # send_message/edit_message own those verbs on Cordless itself (app.py)
    # and delegate to messages.py; channel.send()/message.edit() reach the
    # fuller field set.
    fetch_channel_messages = _delegate(messages.fetch_channel_messages)
    fetch_message = _delegate(messages.fetch_message)
    crosspost_message = _delegate(messages.crosspost_message)
    bulk_delete_messages = _delegate(messages.bulk_delete_messages)
    create_reaction = _delegate(messages.create_reaction)
    delete_own_reaction = _delegate(messages.delete_own_reaction)
    delete_user_reaction = _delegate(messages.delete_user_reaction)
    fetch_reactions = _delegate(messages.fetch_reactions)
    delete_all_reactions = _delegate(messages.delete_all_reactions)
    delete_all_reactions_for_emoji = _delegate(messages.delete_all_reactions_for_emoji)
    search_guild_messages = _delegate(messages.search_guild_messages)
    fetch_poll_answer_voters = _delegate(messages.fetch_poll_answer_voters)
    expire_poll = _delegate(messages.expire_poll)

    # -- members and roles --
    fetch_guild_member = _delegate(members.fetch_guild_member)
    fetch_guild_members = _delegate(members.fetch_guild_members)
    search_guild_members = _delegate(members.search_guild_members)
    add_guild_member = _delegate(members.add_guild_member)
    edit_guild_member = _delegate(members.edit_guild_member)
    edit_current_member = _delegate(members.edit_current_member)
    add_guild_member_role = _delegate(members.add_guild_member_role)
    remove_guild_member_role = _delegate(members.remove_guild_member_role)
    remove_guild_member = _delegate(members.remove_guild_member)
    fetch_guild_roles = _delegate(members.fetch_guild_roles)
    fetch_guild_role = _delegate(members.fetch_guild_role)
    fetch_guild_role_member_counts = _delegate(members.fetch_guild_role_member_counts)
    create_guild_role = _delegate(members.create_guild_role)
    edit_guild_role_positions = _delegate(members.edit_guild_role_positions)
    edit_guild_role = _delegate(members.edit_guild_role)
    delete_guild_role = _delegate(members.delete_guild_role)

    # -- guilds --
    fetch_guild = _delegate(guilds.fetch_guild)
    fetch_guild_preview = _delegate(guilds.fetch_guild_preview)
    edit_guild = _delegate(guilds.edit_guild)
    fetch_guild_bans = _delegate(guilds.fetch_guild_bans)
    fetch_guild_ban = _delegate(guilds.fetch_guild_ban)
    create_guild_ban = _delegate(guilds.create_guild_ban)
    remove_guild_ban = _delegate(guilds.remove_guild_ban)
    bulk_guild_ban = _delegate(guilds.bulk_guild_ban)
    fetch_guild_prune_count = _delegate(guilds.fetch_guild_prune_count)
    begin_guild_prune = _delegate(guilds.begin_guild_prune)
    fetch_guild_voice_regions = _delegate(guilds.fetch_guild_voice_regions)
    fetch_guild_invites = _delegate(guilds.fetch_guild_invites)
    fetch_guild_integrations = _delegate(guilds.fetch_guild_integrations)
    delete_guild_integration = _delegate(guilds.delete_guild_integration)
    fetch_guild_widget_settings = _delegate(guilds.fetch_guild_widget_settings)
    edit_guild_widget = _delegate(guilds.edit_guild_widget)
    fetch_guild_widget = _delegate(guilds.fetch_guild_widget)
    fetch_guild_vanity_url = _delegate(guilds.fetch_guild_vanity_url)
    fetch_guild_welcome_screen = _delegate(guilds.fetch_guild_welcome_screen)
    edit_guild_welcome_screen = _delegate(guilds.edit_guild_welcome_screen)
    fetch_guild_onboarding = _delegate(guilds.fetch_guild_onboarding)
    edit_guild_onboarding = _delegate(guilds.edit_guild_onboarding)
    edit_guild_incident_actions = _delegate(guilds.edit_guild_incident_actions)
    # -- channels --
    fetch_channel = _delegate(channels.fetch_channel)
    edit_channel = _delegate(channels.edit_channel)
    delete_channel = _delegate(channels.delete_channel)
    edit_channel_permissions = _delegate(channels.edit_channel_permissions)
    delete_channel_permission = _delegate(channels.delete_channel_permission)
    fetch_channel_invites = _delegate(channels.fetch_channel_invites)
    create_channel_invite = _delegate(channels.create_channel_invite)
    follow_announcement_channel = _delegate(channels.follow_announcement_channel)
    trigger_typing = _delegate(channels.trigger_typing)
    set_voice_channel_status = _delegate(channels.set_voice_channel_status)
    add_group_dm_recipient = _delegate(channels.add_group_dm_recipient)
    remove_group_dm_recipient = _delegate(channels.remove_group_dm_recipient)
    fetch_channel_pins = _delegate(channels.fetch_channel_pins)
    pin_message = _delegate(channels.pin_message)
    unpin_message = _delegate(channels.unpin_message)
    fetch_guild_channels = _delegate(channels.fetch_guild_channels)
    create_guild_channel = _delegate(channels.create_guild_channel)
    edit_guild_channel_positions = _delegate(channels.edit_guild_channel_positions)

    # -- threads --
    start_thread_from_message = _delegate(threads.start_thread_from_message)
    start_thread_without_message = _delegate(threads.start_thread_without_message)
    start_thread_from_forum = _delegate(threads.start_thread_from_forum)
    join_thread = _delegate(threads.join_thread)
    leave_thread = _delegate(threads.leave_thread)
    add_thread_member = _delegate(threads.add_thread_member)
    remove_thread_member = _delegate(threads.remove_thread_member)
    fetch_thread_member = _delegate(threads.fetch_thread_member)
    fetch_thread_members = _delegate(threads.fetch_thread_members)
    fetch_public_archived_threads = _delegate(threads.fetch_public_archived_threads)
    fetch_private_archived_threads = _delegate(threads.fetch_private_archived_threads)
    fetch_joined_private_archived_threads = _delegate(threads.fetch_joined_private_archived_threads)
    fetch_active_guild_threads = _delegate(threads.fetch_active_guild_threads)

    # -- voice --
    fetch_voice_regions = _delegate(voice.fetch_voice_regions)
    fetch_guild_current_voice_state = _delegate(voice.fetch_current_user_voice_state)
    fetch_guild_member_voice_state = _delegate(voice.fetch_user_voice_state)
    edit_guild_current_voice_state = _delegate(voice.edit_current_user_voice_state)
    edit_guild_member_voice_state = _delegate(voice.edit_user_voice_state)


# functools.wraps copied each target's __name__; put the public name back so a
# renamed delegation reads correctly in tracebacks and generated docs. Every
# _delegate() result is a coroutine function carrying __wrapped__, which
# nothing else in the class body is.
for _public_name, _attr in list(vars(RESTMixin).items()):
    if callable(_attr) and hasattr(_attr, "__wrapped__"):
        _attr.__name__ = _public_name
        _attr.__qualname__ = f"RESTMixin.{_public_name}"
